# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GroundTruther
                                 A QGIS plugin
 A toolset for Serafloor Caracterization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-09
        copyright            : (C) 2023 by epinux
        email                : epiesasha@me.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def _bootstrap_venv():
    """Add the plugin's self-contained virtualenv to sys.path.

    GroundTruther's Python dependencies (pandas, opencv, pyqtgraph, numba, ...)
    are installed into a ``.venv`` created alongside the plugin source with
    ``--system-site-packages`` against the same Python QGIS uses.  This makes
    them importable inside QGIS regardless of how QGIS was launched, without
    relying on a profile ``startup.py``.  No-op if the venv is absent.
    """
    import sys
    from pathlib import Path

    plugin_dir = Path(__file__).resolve().parent
    site = (plugin_dir / ".venv" / "lib"
            / f"python{sys.version_info.major}.{sys.version_info.minor}"
            / "site-packages")
    if site.is_dir():
        p = str(site)
        if p not in sys.path:
            # Append so QGIS/system packages keep priority over venv copies.
            sys.path.append(p)


_bootstrap_venv()


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GroundTruther class from file GroundTruther.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .groundtruther import GroundTruther
    return GroundTruther(iface)
