# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GroundTrutherDockWidget
                                 A QGIS plugin
 A toolset for Seafloor Caracterization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-09
        git sha              : $Format:%H$
        copyright            : (C) 2023 by epinux
        email                : epiesasha@me.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import pyqtSignal
from qgis.utils import iface
from qgis.core import Qgis, QgsMessageLog, QgsProject

from qgis.PyQt.QtCore import Qt

import pyqtgraph as pg

from groundtruther.configure import get_settings
from groundtruther.pygui.Ui_groundtruther_dockwidget_base import Ui_GroundTrutherDockWidgetBase
from groundtruther.pygui.hbc_browser_gui import HBCBrowserGui
from groundtruther.pygui.image_metadata_gui import ImageMetadata
from groundtruther.pygui.app_settings_gui import AppSettings
from groundtruther.pygui.kmlsave_gui import SaveKml
from groundtruther.pygui.querybuilder_gui import QueryBuilder
from groundtruther.pygui.grass_settings_gui import GrassSettings
from groundtruther.grassconfig import GrassConfigDialog
import groundtruther.resources_rc  # noqa: F401

# Mixins — each module owns one concern
from groundtruther.mixins.image_browser_mixin import ImageBrowserMixin, MyImageView
from groundtruther.mixins.grass_mixin import GrassIntegrationMixin
from groundtruther.mixins.annotation_editor_mixin import AnnotationEditorMixin
from groundtruther.mixins.settings_mixin import SettingsMixin

from qgis.PyQt.QtWidgets import QLabel, QLineEdit


class GroundTrutherDockWidget(
    QtWidgets.QDockWidget,
    Ui_GroundTrutherDockWidgetBase,
    ImageBrowserMixin,
    GrassIntegrationMixin,
    AnnotationEditorMixin,
    SettingsMixin,
):
    """Main dock widget — thin orchestrator; all logic lives in mixins."""

    closingPlugin = pyqtSignal()
    send_image_path = pyqtSignal(str)
    send_imagemetadata_string = pyqtSignal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.canvas = iface.mapCanvas()
        self.project = QgsProject.instance()
        self.w = HBCBrowserGui()
        self.setupUi(self)
        self.setWidget(self.w)

        self.config = os.path.join(
            os.path.dirname(__file__), 'config/config.yaml')
        self.settings = get_settings(self.config)
        if not self.settings:
            self._open_config_dialog()
            self.settings = get_settings(self.config)
        # Safe defaults so the rest of __init__ never crashes on missing config
        if not self.settings:
            self.settings = {
                "HabCam": {
                    "imagepath": "", "imagemetadata": "", "imageannotation": ""},
                "Mbes": {"soundings": ""},
                "Export": {"kmldir": ""},
                "Processing": {
                    "gpu_avaibility": False, "grass_api_endpoint": ""},
                "Filesystem": {"filemanager": ""},
            }

        self.grass_dialog = GrassConfigDialog(self)
        self.imagelist = []
        self.imageindex = 0
        self.rangevalue = self.w.range.value()
        self.dirname = self.settings["HabCam"]["imagepath"]
        self.metadatafile = self.settings["HabCam"]["imagemetadata"]
        self.imageannotationfile = self.settings["HabCam"]["imageannotation"]
        self.grass_api_endpoint = self.settings["Processing"]["grass_api_endpoint"]
        self.annotation_confidence_treshold = (
            self.w.annotation_confidence_spinBox.value()
        )
        self.graph_items = []
        self.m1 = None
        self.r = None
        self.imageMetadata = None          # initialised here; set by _apply_settings
        self.image_point_built = False
        self.parsed_query = None
        self.annotation_box_linewidth = 1
        self.annotation_box_vertexsize = 15
        # Metadata panel widget references — populated by _build_metadata_panel()
        self._meta_widgets: dict = {}
        self._meta_time_widget = None

        self.grassenabled = False

        self.init_ui()

        self.w.gisTools.hide()
        self.w.gisTools_logger.hide()
        self.w.actionGisTools.setVisible(True)
        self.w.actionQuit.setVisible(False)

        QgsMessageLog.logMessage(
            f"GroundTruther dock widget initialised (iface: {iface})",
            'GroundTruther', Qgis.Information)

    # ------------------------------------------------------------------ #
    # UI construction                                                      #
    # ------------------------------------------------------------------ #

    def init_ui(self):
        """Build and wire the full UI.

        Delegates specialised concerns to each mixin's ``_init_*`` method so
        this method stays readable as a high-level overview of the layout.
        """
        self.region_response = None

        # --- Central image viewer ---
        self.imv = MyImageView(self.w)
        self.w.setCentralWidget(self.imv)
        self.imv.mousePressEventSignal.connect(self.setStausMessage)

        # --- Misc supporting objects ---
        self.appsettings = AppSettings()
        self.grass_config_widget = GrassSettings()
        self.w.toolWidget.hide()
        self.w.gisTools.hide()

        # --- Status-bar lat/lon display ---
        self.image = QLabel()
        self.w.latitude = QLineEdit()
        self.w.longitude = QLineEdit()
        self.w.longitude.setFocusPolicy(Qt.NoFocus)
        self.w.latitude.setFocusPolicy(Qt.NoFocus)
        self.w.latitude.setFixedWidth(90)
        self.w.longitude.setFixedWidth(90)
        self.w.longitude.setText("0")
        self.w.latitude.setText("0")
        self.w.statusbar.addPermanentWidget(self.w.latitude, stretch=0)
        self.w.statusbar.addPermanentWidget(self.w.longitude, stretch=0)

        # --- Toolbar + menu wiring for settings / tools visibility ---
        self.w.actionTools.triggered.connect(self.showTools)
        self.w.actionGisTools.triggered.connect(self.showGisTools)
        self.w.actionWizard.triggered.connect(self.show_dialog)

        # --- Tool tabs ---
        self.imagemetadata_gui = ImageMetadata()
        self.w.tools.insertTab(0, self.imagemetadata_gui, "Image Metadata")

        self.savekml = SaveKml(self)
        self.send_image_path.connect(self.savekml.from_main_imagepath_signal)
        self.send_imagemetadata_string.connect(
            self.savekml.from_main_imagemetadata_signal)
        self.w.tools.insertTab(1, self.savekml, "Report Builder")

        self.querybuilder = QueryBuilder(self)
        self.w.tools.insertTab(2, self.querybuilder, "BS Query Builder")

        self.querybuilder.send_2dgraph_path.connect(
            self.savekml.from_querybuilder_2dplot_signal)
        self.querybuilder.send_3dgraph_path.connect(
            self.savekml.from_querybuilder_3dplot_signal)
        self.querybuilder.send_selected_points_path.connect(
            self.savekml.from_querybuilder_selected_points_signal)

        # --- Mixin initialisation (order matters) ---
        self._init_image_browser()      # ImageBrowserMixin
        self._apply_settings()          # SettingsMixin — loads data
        self._init_annotation_editor()  # AnnotationEditorMixin
        self._init_grass()              # GrassIntegrationMixin

        self.w.show()

    # ------------------------------------------------------------------ #
    # Simple UI-visibility toggles (too small to deserve a mixin)         #
    # ------------------------------------------------------------------ #

    def showTools(self):
        if self.w.toolWidget.isVisible():
            self.w.toolWidget.hide()
        else:
            self.w.toolWidget.show()

    def showGisTools(self):
        if self.w.gisTools.isVisible():
            self.w.gisTools.hide()
            self.w.gisTools_logger.hide()
        else:
            self.w.gisTools.show()

    # ------------------------------------------------------------------ #
    # Teardown                                                             #
    # ------------------------------------------------------------------ #

    def closeEvent(self, event):
        # Tear down annotation editor before Qt starts destroying widgets.
        if hasattr(self, 'annotation_editor'):
            try:
                self.annotation_editor.cleanup()
            except Exception:
                pass

        # Remove canvas items only if the canvas scene is still alive.
        try:
            scene = self.canvas.scene() if self.canvas else None
            if scene is not None:
                if self.r is not None:
                    scene.removeItem(self.r)
                if self.m1 is not None:
                    scene.removeItem(self.m1)
        except Exception:
            pass

        self.closingPlugin.emit()
        event.accept()
