# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GroundTruther
                                 A QGIS plugin
 A toolset for Seafloor Characterisation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-09
        git sha              : $Format:%H$
        copyright            : (C) 2023 by epinux
        email                : epiesasha@me.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

Plugin entry point — QGIS calls ``classFactory()`` (in ``__init__.py``) which
returns an instance of ``GroundTruther``.

Architecture overview
---------------------
GroundTruther (this file)
    Thin plugin class.  Registers the toolbar and three map tools, then
    delegates all UI logic to ``GroundTrutherDockWidget``.

GroundTrutherDockWidget  (groundtruther_dockwidget.py)
    Main dock widget.  Inherits from four mixins:
      - ImageBrowserMixin  — image navigation, display, metadata panel
      - GrassIntegrationMixin — GRASS API connectivity and region setting
      - AnnotationEditorMixin — floating annotation-editor dock
      - SettingsMixin — configuration loading and the settings dialog

Map tools (maptools/qgsmaptools.py)
    QueryTool     — emits lat/lon on click → drives image index
    GRQueryTool   — same + triggers GRASS r.what raster query
    GCRTool       — rubber-band rectangle → sets GRASS computational region
"""
import os, sys
sys.path.append(os.path.dirname(__file__))

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon, QCursor
from qgis.PyQt.QtWidgets import QAction, QComboBox, QMenu #, 
# Initialize Qt resources from file resources.py

from .resources_rc import *

from qgis.gui import QgsMapToolEmitPoint
import groundtruther.resources_rc

from qgis.core import Qgis, QgsMapLayerType, QgsMessageLog

# Import the code for the DockWidget
from .groundtruther_dockwidget import GroundTrutherDockWidget
import os.path
from groundtruther.maptools.qgsmaptools import GRQueryTool, QueryTool, GCRTool



class GroundTruther:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # self.action_import_raster = QAction( u"Import selected layer into GRASS Server")
        # self.action_import_raster.triggered.connect(lambda: print('raster action triggered - import'))
        # self.action_set_computational_region_from_raster = QAction( u"Set GRASS Server Computational Region to layer extent")
        # self.action_set_computational_region_from_raster.triggered.connect(lambda: print('raster action triggered - set region'))
        # self.iface.addCustomActionForLayerType(self.action_import_raster, 'GroundTruther', QgsMapLayerType.RasterLayer, True)
        # self.iface.addCustomActionForLayerType(self.action_set_computational_region_from_raster, 'GroundTruther', QgsMapLayerType.RasterLayer, True)
        
        # self.action_import_vector = QAction( u"Import selected layer into GRASS Server")
        # self.action_import_vector.triggered.connect(lambda: print('vector action triggered - import'))
        # self.action_set_computational_region_from_vector = QAction( u"Set GRASS Server Computational Region to layer extent")
        # self.action_set_computational_region_from_vector.triggered.connect(lambda: print('vector action triggered - set region'))
        # self.iface.addCustomActionForLayerType(self.action_import_vector, 'GroundTruther', QgsMapLayerType.VectorLayer, True)
        # self.iface.addCustomActionForLayerType(self.action_set_computational_region_from_vector, 'GroundTruther', QgsMapLayerType.VectorLayer, True)
        
        # # Create the main action that triggers the submenu
        # self.main_action = QAction("Custom Menu", self.iface.mainWindow())
        # self.main_action.triggered.connect(lambda: self.show_custom_submenu(self.iface.activeLayer()))
        # self.iface.addCustomActionForLayerType(self.main_action, 'My new Vector Menu', QgsMapLayerType.VectorLayer, True)

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GroundTruther_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GroundTruther')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'GroundTruther')
        self.toolbar.setObjectName(u'GroundTruther')

        #print "** INITIALIZING GroundTruther"

        self.pluginIsActive = False
        self.dockwidget = None

    # def show_custom_submenu(self, layer):
    #     # Create the submenu
    #     submenu = QMenu("Custom Submenu", self.iface.mainWindow())

    #     # Add actions to the submenu
    #     self.action1 = QAction("Custom Action 1", self.iface.mainWindow())
    #     self.action1.triggered.connect(lambda: self.custom_action("Action 1", layer))
    #     submenu.addAction(self.action1)
        
    #     self.action2 = QAction("Custom Action 2", self.iface.mainWindow())
    #     self.action2.triggered.connect(lambda: self.custom_action("Action 2", layer))
    #     submenu.addAction(self.action2)
        
    #     # Show the submenu at the current mouse position
    #     submenu.exec_(QCursor.pos())

    # def custom_action(self, action_name, layer):
    #     self.iface.messageBar().pushMessage("Custom Action", f"{action_name} triggered on layer: {layer.name()}")

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GroundTruther', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
        hasmaptools=False,
        maptool=None,
        maptool_callback=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        # if hasmaptools:
        #     action.setCheckable(True)
        #     self.pointTool = GRQueryTool(self.iface.mapCanvas())
        #     self.pointTool.setAction(action)
        #     self.pointTool.grass_raster_query.connect(self.printmessage)
            
            #self.pointTool.canvasClicked.connect(self.printevent)
        if hasmaptools:
            action.setCheckable(True)
            mapTool = maptool(self.iface.mapCanvas())# QueryTool(self.iface.mapCanvas())
            mapTool.setAction(action)
            
            mapTool.query_position.connect(maptool_callback)
            
        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        # return action
        if hasmaptools:
            return mapTool


    def select_grass_cpr(self, index):
        """Forward a saved-region selection by index to the dockwidget."""
        if self.pluginIsActive:
            self.dockwidget.select_grass_cpr(index)

    def set_grass_cpr(self, minlat: float, maxlat: float, minlon: float, maxlon: float):
        """Forward a rubber-band bounding box to the dockwidget GRASS mixin.

        Called by the ``GCRTool.grass_computational_region`` signal after the
        user finishes drawing a rectangle on the map canvas.
        """
        if self.pluginIsActive:
            self.dockwidget.set_grass_cpr(minlat, maxlat, minlon, maxlon)

    def set_image_index(self, lat: float, lon: float):
        """Find and display the image nearest to the clicked map coordinate.

        Called by the ``QueryTool.query_position`` signal.
        """
        if self.pluginIsActive:
            self.dockwidget.get_query_position(lat, lon)

    def query(self):
        """Activate the point-query map tool on the canvas."""
        self.iface.mapCanvas().setMapTool(self.pointTool)
        QgsMessageLog.logMessage(
            f"query tool active, pluginIsActive={self.pluginIsActive}",
            'GroundTruther', Qgis.Info)

    def print_message_old(self, grass_raster_query: object):
        """Forward a raw GRASS raster-query result string to the dockwidget.

        Legacy slot connected to ``GRQueryTool.grass_raster_query``.
        """
        QgsMessageLog.logMessage(
            f"grass_raster_query: {grass_raster_query}", 'GroundTruther', Qgis.Info)
        if self.pluginIsActive:
            self.dockwidget.get_query_message(grass_raster_query)

    def print_message(self, lat: float, lon: float):
        """Forward a map-click position to the GRASS r.what query handler.

        Called by ``GRQueryTool.query_position``; the dockwidget's GRASS mixin
        converts the coordinates to a GRASS API request.
        """
        if self.pluginIsActive:
            self.dockwidget.get_grass_query_data(lat, lon)

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/icons/qtui/icons/epi.gif'
        self.add_action(
            icon_path,
            text=self.tr(u'GroundTruther'),
            callback=self.run,
            parent=self.iface.mainWindow())
        icon_path = ':/icons/qtui/icons/epi.gif'
        
        # self.query_tool = self.add_action(
        #     icon_path,
        #     text=self.tr(u'GroundTruther'),
        #     callback=self.query,
        #     parent=self.iface.mainWindow(),
        #     hasmaptools=True,
        #     maptool=QueryTool,
        #     maptool_callback=self.print_coords)
        

        image_query_icon_path = ':/icons/qtui/icons/target.png'
        image_query_icon = QIcon(image_query_icon_path)
        image_query_action = QAction(image_query_icon, self.tr(u'Image Browser'), self.iface.mainWindow())
        #
        image_query_action.triggered.connect(self.image_query)
        image_query_action.setEnabled(True)
        image_query_action.setCheckable(True)
        #
        self.image_query_tool = QueryTool(self.iface.mapCanvas())# QueryTool(self.iface.mapCanvas())
        self.image_query_tool.setAction(image_query_action)
        #
        self.image_query_tool.query_position.connect(self.set_image_index)
        
        self.toolbar.addAction(image_query_action)
        self.iface.addPluginToMenu(
            self.menu,
            image_query_action)
        self.actions.append(image_query_action)

        
        grass_query_icon_path = ':/icons/qtui/icons/gui-query.gif'
        grass_query_icon = QIcon(grass_query_icon_path)
        grass_query_action = QAction(grass_query_icon, self.tr(u'GRASS Query'), self.iface.mainWindow())
        #
        grass_query_action.triggered.connect(self.grass_query)
        grass_query_action.setEnabled(True)
        grass_query_action.setCheckable(True)
        #
        self.grass_query_tool = GRQueryTool(self.iface.mapCanvas())# QueryTool(self.iface.mapCanvas())
        self.grass_query_tool.setAction(grass_query_action)
        #
        self.grass_query_tool.grass_raster_query.connect(self.print_message_old)
        self.grass_query_tool.query_position.connect(self.print_message)
        
        self.toolbar.addAction(grass_query_action)
        self.iface.addPluginToMenu(
            self.menu,
            grass_query_action)
        self.actions.append(grass_query_action)
        
        
        grass_cpr_icon_path = ':/icons/qtui/icons/mActionSelectRectangle.svg'
        grass_cpr_icon = QIcon(grass_cpr_icon_path)
        grass_cpr_action = QAction(grass_cpr_icon, self.tr(u'GRASS Computational Region'), self.iface.mainWindow())
        #
        grass_cpr_action.triggered.connect(self.grass_cpr)
        grass_cpr_action.setEnabled(True)
        grass_cpr_action.setCheckable(True)
        #
        self.grass_cpr_tool = GCRTool(self.iface.mapCanvas())# QueryTool(self.iface.mapCanvas())
        self.grass_cpr_tool.setAction(grass_cpr_action)
        #
        # self.grass_cpr_tool.grass_computational_region.connect(self.print_bounds)
        self.grass_cpr_tool.grass_computational_region.connect(self.set_grass_cpr)
        
        self.toolbar.addAction(grass_cpr_action)
        
        # the code below will be useful when we have a method to select a saved region
        # first we need to have a method to save a region
        # then we need to have a list of saved regions and pass it into the combo box
        #
        # self.select_region = QComboBox()
        # self.toolbar.addWidget(self.select_region)
        # self.select_region.insertItems(1,["Region 1","Region 2","Region 3", "Region 4"])
        # self.select_region.currentIndexChanged.connect(self.select_grass_region)
        # self.select_region.setToolTip("select_grass_region")
        
        self.iface.addPluginToMenu(
            self.menu,
            grass_cpr_action)
        self.actions.append(grass_cpr_action)
        
        #a = QAction( u"My Raster Action")
        #a.triggered.connect(lambda: print('action triggered'))
        #self.iface.addCustomActionForLayerType(a, 'My Raster Menu', QgsMapLayerType.RasterLayer, True)
        
        
    # def select_grass_region(self, index):
    #     print(index)
        
    
    # def grquery(self):
    #     """
    #     Activate the query tool
    #     """
    #     self.iface.mapCanvas().setMapTool(self.pointTool)
    #     print(self.pluginIsActive)

    def grass_cpr(self):
        """Activate the GCRTool (rubber-band rectangle for GRASS region selection)."""
        self.iface.mapCanvas().setMapTool(self.grass_cpr_tool)

    def image_query(self):
        """Activate the QueryTool (nearest-image lookup on map click)."""
        self.iface.mapCanvas().setMapTool(self.image_query_tool)

    def grass_query(self):
        """Activate the GRQueryTool (GRASS r.what raster-value query on map click)."""
        self.iface.mapCanvas().setMapTool(self.grass_query_tool)
    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING GroundTruther"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        # If one of our map tools is active, unset it before destroying it.
        # Leaving an active tool pointing at a deleted object causes SIGSEGV.
        our_tools = [
            getattr(self, 'image_query_tool', None),
            getattr(self, 'grass_query_tool', None),
            getattr(self, 'grass_cpr_tool', None),
        ]
        try:
            canvas = self.iface.mapCanvas()
            if canvas.mapTool() in our_tools:
                canvas.unsetMapTool(canvas.mapTool())
        except Exception:
            pass

        # Clean up the GCRTool rubber band before the canvas scene is torn down.
        if getattr(self, 'grass_cpr_tool', None) is not None:
            try:
                self.grass_cpr_tool.reset()
            except Exception:
                pass

        if self.dockwidget is not None:
            # Close pyqtgraph ImageView before C++ widget destruction so that
            # ViewBox.AllViews is cleaned up while the scene is still valid.
            # (removeDockWidget does not trigger closeEvent on a docked widget,
            # so this must be done explicitly here.)
            if hasattr(self.dockwidget, 'imv'):
                try:
                    if hasattr(self.dockwidget.imv, 'view'):
                        self.dockwidget.imv.view.close()
                    self.dockwidget.imv.close()
                except Exception:
                    pass

            if getattr(self.dockwidget, 'grass_dialog', None) is not None and self.dockwidget.grass_dialog.grassenabled:
                self.iface.removeCustomActionForLayerType(self.dockwidget.action_import_raster)
                self.iface.removeCustomActionForLayerType(self.dockwidget.action_set_computational_region_from_raster)
                self.iface.removeCustomActionForLayerType(self.dockwidget.action_import_vector)
                self.iface.removeCustomActionForLayerType(self.dockwidget.action_set_computational_region_from_vector)
            self.iface.removeDockWidget(self.dockwidget)
            # Schedule C++ deletion for the next event-loop iteration (safe),
            # then release the Python reference immediately.  Without this the
            # old dockwidget is GC'd at an arbitrary later time — potentially
            # mid-operation in the next plugin load — causing further crashes.
            self.dockwidget.deleteLater()
            self.dockwidget = None
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GroundTruther'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------



    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            QgsMessageLog.logMessage("** STARTING GroundTruther", 'GroundTruther', Qgis.Info)

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget is None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = GroundTrutherDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
            if self.dockwidget is not None:
                if self.dockwidget.m1 is not None:
                    self.iface.mapCanvas().scene().addItem(self.dockwidget.m1)
                if self.dockwidget.r is not None:
                    self.iface.mapCanvas().scene().addItem(self.dockwidget.r)
