# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/epsg_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(298, 254)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/600px-Brosen_windrose.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Code_rb = QtWidgets.QRadioButton(self.groupBox)
        self.Code_rb.setObjectName("Code_rb")
        self.horizontalLayout.addWidget(self.Code_rb)
        self.Params_rb = QtWidgets.QRadioButton(self.groupBox)
        self.Params_rb.setObjectName("Params_rb")
        self.horizontalLayout.addWidget(self.Params_rb)
        self.Title_rb = QtWidgets.QRadioButton(self.groupBox)
        self.Title_rb.setObjectName("Title_rb")
        self.horizontalLayout.addWidget(self.Title_rb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Code_cb = QtWidgets.QCheckBox(self.groupBox)
        self.Code_cb.setObjectName("Code_cb")
        self.horizontalLayout_2.addWidget(self.Code_cb)
        self.Params_cb = QtWidgets.QCheckBox(self.groupBox)
        self.Params_cb.setObjectName("Params_cb")
        self.horizontalLayout_2.addWidget(self.Params_cb)
        self.Title_cb = QtWidgets.QCheckBox(self.groupBox)
        self.Title_cb.setObjectName("Title_cb")
        self.horizontalLayout_2.addWidget(self.Title_cb)
        self.All_cb = QtWidgets.QCheckBox(self.groupBox)
        self.All_cb.setObjectName("All_cb")
        self.horizontalLayout_2.addWidget(self.All_cb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Search = QtWidgets.QToolButton(self.groupBox)
        self.Search.setStyleSheet(" QToolButton { /* all types of tool button */\n"
"     border: 2px solid #8f8f91;\n"
"     border-radius: 6px;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
" }\n"
"\n"
" QToolButton[popupMode=\"1\"] { /* only for MenuButtonPopup */\n"
"     padding-right: 20px; /* make way for the popup button */\n"
" }\n"
"\n"
" QToolButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }\n"
"\n"
" QToolButton:checked {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 white, stop: 1 blue);\n"
" }\n"
"\n"
" /* the subcontrols below are used only in the MenuButtonPopup mode */\n"
" QToolButton::menu-button {\n"
"     border: 2px solid gray;\n"
"     border-top-right-radius: 6px;\n"
"     border-bottom-right-radius: 6px;\n"
"     /* 16px width + 4px for border = 20px allocated above */\n"
"     width: 16px;\n"
" }\n"
"\n"
" QToolButton::menu-arrow {\n"
"     image: url(downarrow.png);\n"
" }\n"
"\n"
" QToolButton::menu-arrow:open {\n"
"     top: 1px; left: 1px; /* shift it a bit */\n"
" }")
        self.Search.setObjectName("Search")
        self.horizontalLayout_4.addWidget(self.Search)
        self.OutList = QtWidgets.QComboBox(self.groupBox)
        self.OutList.setObjectName("OutList")
        self.horizontalLayout_4.addWidget(self.OutList)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.printout = QtWidgets.QTextEdit(Form)
        self.printout.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.printout.setObjectName("printout")
        self.verticalLayout_3.addWidget(self.printout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Epsg"))
        self.Code_rb.setText(_translate("Form", "Code"))
        self.Params_rb.setText(_translate("Form", "Params"))
        self.Title_rb.setText(_translate("Form", "Title"))
        self.Code_cb.setText(_translate("Form", "Code"))
        self.Params_cb.setText(_translate("Form", "Param"))
        self.Title_cb.setText(_translate("Form", "Title"))
        self.All_cb.setText(_translate("Form", "All"))
        self.Search.setText(_translate("Form", "->"))
import groundtruther.resources_rc
