# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/grass_mdi_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_grass_mdi(object):
    def setupUi(self, grass_mdi):
        grass_mdi.setObjectName("grass_mdi")
        grass_mdi.resize(301, 220)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(grass_mdi)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(grass_mdi)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.grassTools = QtWidgets.QMdiArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grassTools.sizePolicy().hasHeightForWidth())
        self.grassTools.setSizePolicy(sizePolicy)
        self.grassTools.setMinimumSize(QtCore.QSize(0, 0))
        self.grassTools.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grassTools.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.grassTools.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.grassTools.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.grassTools.setActivationOrder(QtWidgets.QMdiArea.StackingOrder)
        self.grassTools.setTabsMovable(True)
        self.grassTools.setObjectName("grassTools")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.zoom_in = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/qtui/icons/mActionIncreaseFont.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in.setIcon(icon)
        self.zoom_in.setAutoRepeat(True)
        self.zoom_in.setObjectName("zoom_in")
        self.horizontalLayout.addWidget(self.zoom_in)
        self.zoom_out = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/qtui/icons/mActionDecreaseFont.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out.setIcon(icon1)
        self.zoom_out.setAutoRepeat(True)
        self.zoom_out.setObjectName("zoom_out")
        self.horizontalLayout.addWidget(self.zoom_out)
        self.selectAll = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/qtui/icons/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectAll.setIcon(icon2)
        self.selectAll.setObjectName("selectAll")
        self.horizontalLayout.addWidget(self.selectAll)
        self.copy = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.copy.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/qtui/icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy.setIcon(icon3)
        self.copy.setObjectName("copy")
        self.horizontalLayout.addWidget(self.copy)
        self.clear = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/qtui/icons/eraser.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear.setIcon(icon4)
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gis_tool_report = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.gis_tool_report.setObjectName("gis_tool_report")
        self.verticalLayout.addWidget(self.gis_tool_report)
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(grass_mdi)
        QtCore.QMetaObject.connectSlotsByName(grass_mdi)

    def retranslateUi(self, grass_mdi):
        _translate = QtCore.QCoreApplication.translate
        grass_mdi.setWindowTitle(_translate("grass_mdi", "Form"))
        self.zoom_in.setText(_translate("grass_mdi", "..."))
        self.zoom_out.setText(_translate("grass_mdi", "..."))
        self.selectAll.setText(_translate("grass_mdi", "..."))
        self.clear.setText(_translate("grass_mdi", "..."))
import groundtruther.resources_rc
