# Form implementation generated from reading ui file 'qtui/groundtruther_dockwidget_base.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_GroundTrutherDockWidgetBase(object):
    def setupUi(self, GroundTrutherDockWidgetBase):
        GroundTrutherDockWidgetBase.setObjectName("GroundTrutherDockWidgetBase")
        GroundTrutherDockWidgetBase.resize(232, 141)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        GroundTrutherDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(GroundTrutherDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(GroundTrutherDockWidgetBase)

    def retranslateUi(self, GroundTrutherDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        GroundTrutherDockWidgetBase.setWindowTitle(_translate("GroundTrutherDockWidgetBase", "GroundTruther"))
        self.label.setText(_translate("GroundTrutherDockWidgetBase", "Replace this QLabel\n"
"with the desired\n"
"plugin content."))
