---
Filesystem:
    filemanager: C:/Users/Field/Downloads/groundtruther_test_dataset/groundtruther_test_dataset/mbes_2015.parquet
HabCam:
    imagepath: C:/Users/Field/Downloads/groundtruther_test_dataset/groundtruther_test_dataset/image_subset
    imagemetadata: C:/Users/Field/Downloads/groundtruther_test_dataset/groundtruther_test_dataset/test_imagemetadata.pq
    imageannotation: C:/Users/Field/Downloads/groundtruther_test_dataset/groundtruther_test_dataset/test_detector_output.csv
Mbes:
    soundings: C:/Users/Field/Downloads/groundtruther_test_dataset/groundtruther_test_dataset/mbes_2015.parquet
Export:
    kmldir: C:/Users/Field/Desktop/kml
Processing:
    gpu_avaibility: False
    grass_api_endpoint: https://mbapi.wps.met.no