---
Filesystem:
    filemanager: 
HabCam:
    imagepath: C:/Users/massi/DEV/QGIS_PLUGIN/groundtruther_test_dataset/image_subset
    imagemetadata: C:/Users/massi/DEV/QGIS_PLUGIN/groundtruther_test_dataset/test_imagemetadata.parquet
    imageannotation: C:/Users/massi/DEV/QGIS_PLUGIN/groundtruther_test_dataset/test_detector_output.csv
Mbes:
    soundings: C:/Users/massi/DEV/QGIS_PLUGIN/groundtruther_test_dataset/mbes_2015.parquet
Export:
    kmldir: C:/Users/massi/DEV/QGIS_PLUGIN/groundtruther_test_dataset
Processing:
    gpu_avaibility: False
    grass_api_endpoint: https://mbapi.wps.met.no