---
Filesystem:
    filemanager: {{filemanager}}
HabCam:
    imagepath: {{imagepath}}
    imagemetadata: {{imagemetadata}}
    imageannotation: {{imageannotation}}
Mbes:
    soundings: {{soundings}}
    reference_surface: {{reference_surface}}
Export:
    kmldir: {{kmldir}}
Processing:
    gpu_avaibility: {{gpu_avaibility}}
    grass_api_endpoint: {{grass_api_endpoint}}
    grass_api_key: {{grass_api_key}}
Video:
    videofile: {{videofile}}
    videometadata: {{videometadata}}
    videoannotation: {{videoannotation}}
Session:
    groundtruther_project: {{groundtruther_project}}